services:
  postgres:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
    - 5432:5432
    volumes:
    - /Projects/dockerImages/postgresql/data
    

